#!/bin/bash
find . name \*.js"\ -type f -delete>>10-no_more_js

10-no_more_js
echo find . name \\*.js"\ -type f -delete
find . name \*.js"\ -type f -delete>>10-no_more_js  
echo find . name \\*.js"\ -type f -delete
