#!/bin/bash
grep -c bin /etc/passwd'>>15-countthatword
echo grep -c bin /etc/passwd>>15-countthatword
chmod u+x 15-countthatword
echo "grep -c bin /etc/passwd
grep -c bin /etc/passwd'>>15-countthatword
chmod u+x 15-countthatword
echo grep -c bin /etc/passwd>>15-countthatword
chmod u+x 15-countthatword

chmod u+x 12-newest_files
15-countthatword
echo "grep -c bin /etc/passwd
grep -c bin /etc/passwd'>>15-countthatword
chmod u+x 15-countthatword
echo grep -c bin /etc/passwd>>15-countthatword







echo "grep -c bin /etc/passwd
grep -c bin /etc/passwd'>>15-countthatword
chmod u+x 15-countthatword

chmod u+x 12-newest_files
15-countthatword
echo grep -c bin /etc/passwd>>15-countthatword
;Q1
:q1
git add .
git commit -m 15-countthatword
git push
echo "grep -c bin /etc/passwd
grep -c bin /etc/passwd'>>15-countthatword
;Q1
:q1
git add .
git commit -m '15-countthatword'
git push
chmod u+x 12-newest_files
echo grep -c bin /etc/passwd>>15-countthatword
chmod u+x 15-countthatword
echo "grep -c bin /etc/passwd
grep -c bin /etc/passwd'>>15-countthatword
chmod u+x 13-unique





















i

echo grep -c bin /etc/passwd>>15-countthatword
chmod u+x 13-unique





















i


echo "grep -c bin /etc/passwd
grep -c bin /etc/passwd'>>15-countthatword
chmod u+x 15-countthatword
echo grep -c bin /etc/passwd>>15-countthatword
echo "grep -c bin /etc/passwd
